api = "0.10"

[buildpack]
id = "fagianijunior/google-chrome"
version = "1.0.5"
name = "Google Chrome"
homepage = "https://github.com/fagianijunior/heroku-buildpack-chrome-for-testing"
description = ""
keywords = ["chrome", "tar", "tarball", "tgz", "archives", "build", "write", "external", "files", "browser"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "*"
